kubectl apply -f k8s_config/services/mysql/mysql-deployment.yaml

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -13,6 +13,7 @@ jobs:
       MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
       MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
       MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
+      KUBECONFIG: ${{ secrets.KUBECONFIG }}
 
     steps:
     - name: Checkout repository
@@ -22,13 +23,36 @@ jobs:
       uses: azure/setup-kubectl@v3
       with:
         version: 'latest'
+        
+    - name: Check Secrets
+      run: |
+        #!/bin/bash
+        if [ -z "$MYSQL_USER" ]; then
+          echo "Error: MYSQL_USER is empty or null"
+          exit 1
+        fi
+        if [ -z "$MYSQL_DATABASE" ]; then
+          echo "Error: MYSQL_DATABASE is empty or null"
+          exit 1
+        fi
+        if [ -z "$MYSQL_ROOT_PASSWORD" ]; then
+          echo "Error: MYSQL_ROOT_PASSWORD is empty or null"
+          exit 1
+        fi
+        if [ -z "$MYSQL_PASSWORD" ]; then
+          echo "Error: MYSQL_PASSWORD is empty or null"
+          exit 1
+        fi
+        if [ -z "$KUBECONFIG" ]; then
+          echo "Error: KUBECONFIG is empty or null"
+          exit 1
+        fi
+        echo "All secrets are present and have values."
 
     - name: Set up Kubeconfig
-      env:
-        KUBECONFIG: ${{ secrets.KUBECONFIG }}
       run: |
         mkdir -p ~/.kube
-        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
+        echo "$KUBECONFIG" > ~/.kube/config
 
     - name: Deploy application to Kubernetes
       run: |
